### ISSUE TITLE
Error opening File

### ISSUE THREAD

**Issue by brandon-a** [brandon-a/CIS-22C-Group-Project#2] opened 2015-11-24 02:42 UTC
inFile.open("..\ResourceFile\USDA_data_small.txt");

Opening the file as shown above produces an error. How would we go about opening the file that is in the ResourceFile folder?

**Comment by theorangepotato** [comment] 2015-11-24 06:04
The problem is the backslashes (). They are really only used in the Windows file system, most other OSes (Unix-like) use the slash (/), as does the compiler. Also, a backslash in a string literal needs to be cancelled out by another backslash (\).

But anyway, the answer is to write:
inFile.open("../ResourceFile/USDA_data_small.txt");

This seemed to work for me. I'm closing the issue for now, however, reopen it if it doesn't work for you.

**Closed as completed by theorangepotato** 2015-11-24 06:04 UTC
Labels: bug, help wanted
